routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', '/login');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home')->middleware('auth');
Route::resource('customer',\App\Http\Controllers\CustomerController::class)->middleware('auth');
Route::get('delete/{customer}', [\App\Http\Controllers\CustomerController::class, 'delete'])->name('customer.delete')->middleware('auth');
Route::resource('order',\App\Http\Controllers\OrderController::class)->middleware('auth');
Route::get('deleteOrder/{order}', [\App\Http\Controllers\OrderController::class, 'delete'])->name('order.delete')->middleware('auth');

app/Models/Customer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Order;

class Customer extends Model
{
    use HasFactory;

    /**
     * @var array
    */
    protected $fillable = ['name', 'buildingNumber', 'street', 'city', 'postcode', 'email', 'website', 'user_id'];

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */
    public $timestamps = false;

    /**
     * The storage format of the model's date columns.
     *
     * @var string
     */
    protected $dateFormat = true;

    public function user() {
        return $this->belongsTo('\App\Models\User', 'user_id');
    }

    public function orders() {
        return $this->hasMany(Order::Class);
    }

}

app/Http/Controllers/CustomerController.php
<?php

namespace App\Http\Controllers;

use App\Models\Customer;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class CustomerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $customers = Customer::where('user_id', Auth::id())->get();
        return view('customer.index', [
            'customers' => $customers,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function show(Customer $customer)
    {
        $customers = Customer::All();
        $customer = $customers->find($customer);
        if($customer->user->id == Auth::id()) {
            return view('customer.show', [
                'customer' => $customer,
            ]);
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function edit(Customer $customer)
    {
        $customers = Customer::All();
        $customer = $customers->find($customer);
        if($customer->user->id == Auth::id()) {
            return view('customer.edit', [
                'customer' => $customer,
            ]);
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Customer $customer)
    {
        $customer->update($request->all());
        if($customer->user->id == Auth::id()){
            $customer->save();
        }
        return view('customer.show', [
            'customer' => $customer,
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function destroy(Customer $customer)
    {
        if($customer->user->id == Auth::id()){
            $customer->delete();
        }
        return redirect()->route('customer.index');
    }

    /**
     * Show form to remove the specified resource from storage.
     *
     * @param  \App\Models\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function delete(Customer $customer)
    {
        return view('customer.delete', [
            'customer' => $customer,
        ]);
    }
}

resources/views/customer/delete.blade.php
@extends('adminlte::page')

@section('title', 'AliSales')
@section('content_header')
<h1 class="m-0 text-dark"><?php echo __('main.customer'); ?></h1>
@stop

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-6">
            <form method="POST" action="{{route('customer.destroy', ['customer'=>$customer])}}">
                @csrf
                @method('DELETE')
                <div class="card card-primary card-outline">
                    <div class="card-body">
                        <?php echo __('main.delete_confirm'); ?>
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer">
                        <a href="{{route('customer.index')}}" class="btn btn-default float-left">
                            <?php echo __('main.cancel'); ?>
                        </a>
                        <input type="submit" class="btn btn-danger float-right" value="<?php echo __('main.delete'); ?>">
                    </div>
                </div>
        </div>
        </form>
    </div>
</div>
</div>
@stop

resources/views/customer/edit.blade.php
@extends('adminlte::page')

@section('title', 'AliSales')
@section('content_header')
    <h1 class="m-0 text-dark"><?php echo __('main.customers'); ?></h1>
@stop

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-6">
                <form method="POST" action="{{route('customer.update', ['customer'=>$customer])}}">
                        @csrf
                        @method('PUT')
                        <div class="card-body">
                            <div class="form-group">
                                <label for="name"><?php echo __('main.name'); ?></label>
                                <input type="text" class="form-control" id="name" name="name" value="{{$customer->name}}">
                            </div>
                            <div class="form-group">
                                <label for="name"><?php echo __('main.buildingNumber'); ?></label>
                                <input type="text" class="form-control" id="buildingNumber" name="buildingNumber" value="{{$customer->buildingNumber}}">
                            </div>
                            <div class="form-group">
                                <label for="name"><?php echo __('main.address'); ?></label>
                                <textarea class="form-control" id="address" name="address">{{$customer->street}}</textarea>
                            </div>
                            <div class="form-group">
                                <label for="name"><?php echo __('main.postcode'); ?></label>
                                <input type="text" class="form-control" id="postalCode" name="postalCode" value="{{$customer->postcode}}">
                            </div>
                            <div class="form-group">
                                <label for="name"><?php echo __('main.city'); ?></label>
                                <input type="text" class="form-control" id="city" name="city" value="{{$customer->city}}">
                            </div>
                            <div class="form-group">
                                <label for="name"><?php echo __('main.email'); ?></label>
                                <input type="email" class="form-control" id="email" name="email" value="{{$customer->email}}">
                            </div>
                            <div class="form-group">
                                <label for="name"><?php echo __('main.website'); ?></label>
                                <input type="text" class="form-control" id="website" name="website" value="{{$customer->website}}">
                            </div>
                        </div>
                        <!-- /.card-body -->
                        <div class="card-footer">
                            <input type="submit" class="btn btn-primary float-right">
                        </div>
                    </div>
                </form>
            </div>

        </div>
    </div>
@stop

resources/views/customer/index.blade.php
@extends('adminlte::page')

@section('title', 'AliSales')
@section('content_header')
    <h1 class="m-0 text-dark"><?php echo __('main.customers'); ?></h1>
@stop

@section('content')

    <table id="example" class="table table-bordered table-striped datatable dataTable no-footer" style="width:100%">
        <thead>
        <tr>
            <th><?php echo __('main.name'); ?></th>
            <th><?php echo __('main.address'); ?></th>
            <th><?php echo __('main.email'); ?></th>
            <th><?php echo __('main.website'); ?></th>
            <th></th>
        </tr>
        </thead>
        <tbody>

        <!-- limité à 30 afin que la page ne charge pas tous les éléments -->
        @foreach ($customers as $customer)
            <x-customer.tr :customer=$customer> </x-customer.tr>
        @endforeach

        </tbody>
        <tfoot>
        <tr>
            <th><?php echo __('main.name'); ?></th>
            <th><?php echo __('main.address'); ?></th>
            <th><?php echo __('main.email'); ?></th>
            <th><?php echo __('main.website'); ?></th>
            <th></th>
        </tr>
        </tfoot>
    </table>
@stop
@section('js')
    <script>
        $(document).ready(function () {
            $('#example').DataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/French.json"
                }
            });
        });
    </script>
@stop

resources/views/customer/show.blade.php
@extends('adminlte::page')

@section('title', 'AliSales')
@section('content_header')
    <h1 class="m-0 text-dark"><?php echo __('main.customers'); ?></h1>
@stop

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-3">
                <div class="card card-primary card-outline">
                    <div class="card-body box-profile">
                        <h3 class="profile-username text-center">{{$customer->name}}</h3>

                        <ul class="list-group list-group-unbordered mb-3">
                            <li class="list-group-item">
                                <b><?php echo __('main.address'); ?></b> <span class="float-right">{{$customer->buildingNumber}}, {{$customer->street}}</span>
                            </li>
                            <li class="list-group-item">
                                <b><?php echo __('main.postcode'); ?></b> <span class="float-right">{{$customer->postcode}}</span>
                            </li>
                            <li class="list-group-item">
                                <b><?php echo __('main.city'); ?></b> <span class="float-right">{{$customer->city}}</span>
                            </li>
                            <li class="list-group-item">
                                <b><?php echo __('main.email'); ?></b> <span class="float-right">{{$customer->email}}</span>
                            </li>
                            <li class="list-group-item">
                                <b><?php echo __('main.website'); ?></b>
                                <a class="float-right">
                                    <i class="fa fa-external-link-alt"></i>
                                </a>
                            </li>
                        </ul>

                        <a href="{{route('customer.edit', ['customer'=>$customer])}}" class="btn btn-primary btn-block"><b><?php echo __('main.modify'); ?></b></a>
                    </div>
                    <!-- /.card-body -->
                </div>
            </div>
            <div class="col-9">
                <dic class="card">
                    <div class="card-header">
                        <?php echo __('main.orders'); ?>
                    </div>
                    <div class="card-body">
                        <table id="orders" class="table table-bordered table-striped datatable dataTable no-footer" style="width:100%">
                            <thead>
                            <tr>
                                <th><?php echo __('main.dateTime'); ?></th>
                                <th><?php echo __('main.amount'); ?></th>
                                <th><?php echo __('main.amountVTA'); ?></th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>

                            <!-- limité à 30 afin que la page ne charge pas tous les éléments -->
                            @foreach ($customer->orders as $order)
                                <x-order.tr_customer :order=$order> </x-order.tr_customer>
                            @endforeach

                            </tbody>
                            <tfoot>
                            <tr>
                                <th><?php echo __('main.dateTime'); ?></th>
                                <th><?php echo __('main.amount'); ?></th>
                                <th><?php echo __('main.amountVTA'); ?></th>
                                <th></th>
                            </tr>
                            </tfoot>
                        </table>
                    </div>
                </dic>
            </div>
        </div>
    </div>
@stop