routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', '/login');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home')->middleware('auth');
Route::resource('customer',\App\Http\Controllers\CustomerController::class)->middleware('auth');
Route::get('delete/{customer}', [\App\Http\Controllers\CustomerController::class, 'delete'])->name('customer.delete')->middleware('auth');
Route::resource('order',\App\Http\Controllers\OrderController::class)->middleware('auth');
Route::get('deleteOrder/{order}', [\App\Http\Controllers\OrderController::class, 'delete'])->name('order.delete')->middleware('auth');

app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    use HasFactory;

    /**
     * @var array
     */
    protected $fillable = ['dateTime', 'amount', 'amountVTA'];

    public function customer() {
        return $this->belongsTo('\App\Models\Customer', 'customer_id');
    }

    public function user() {
        return $this->customer->user();
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Models\Order;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $orders = Order::All();
        $user = User::find(Auth::id());
        $orders = $orders->where('user',$user);
        return view('order.index', [
            'orders' => $orders,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function show(Order $order)
    {
        $orders = Order::All();
        $order = $orders->find($order);
        if($order->user->id == Auth::id()) {
            return view('order.show', [
                'order' => $order,
            ]);
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function edit(Order $order)
    {
        $orders = Order::All();
        $order = $orders->find($order);
        if($order->user->id == Auth::id()) {
            return view('order.edit', [
                'order' => $order,
            ]);
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Order $order)
    {
        $order->update([
            'amount'=>$request->amount,
            'amountVTA' => $request->amountVTA
        ]);
        if($order->user->id == Auth::id()){
            $order->save();
        }
        return view('order.show', [
            'order' => $order,
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function destroy(Order $order)
    {
        if($order->user->id == Auth::id()){
            $order->delete();
        }
        return redirect()->route('order.index');
    }

    /**
     * Show form to remove the specified resource from storage.
     *
     * @param  \App\Models\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function delete(Order $order)
    {
        return view('order.delete', [
            'order' => $order,
        ]);
    }
}

resources/views/order/delete.blade.php
@extends('adminlte::page')

@section('title', 'AliSales')
@section('content_header')
<h1 class="m-0 text-dark"><?php echo __('main.order'); ?></h1>
@stop

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-6">
            <form method="POST" action="{{route('order.destroy', ['order'=>$order])}}">
                @csrf
                @method('DELETE')
                <div class="card card-primary card-outline">
                    <div class="card-body">
                        <?php echo __('main.delete_confirm'); ?>
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer">
                        <a href="{{route('order.index')}}" class="btn btn-default float-left">
                            <?php echo __('main.cancel'); ?>
                        </a>
                        <input type="submit" class="btn btn-danger float-right" value="<?php echo __('main.delete'); ?>">
                    </div>
                </div>
        </div>
        </form>
    </div>
</div>
</div>
@stop

resources/views/order/edit.blade.php
@extends('adminlte::page')

@section('title', 'AliSales')
@section('content_header')
    <h1 class="m-0 text-dark"><?php echo __('main.orders'); ?></h1>
@stop

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-6">
                <form method="POST" action="{{route('order.update', ['order'=>$order])}}">
                        @csrf
                        @method('PUT')
                        <div class="card-body">
                            <div class="form-group">
                                <label for="dateTime"><?php echo __('main.dateTime'); ?></label>
                                <input type="datetime-local" id="dateTime"
                                       name="dateTime-time" value="{{$order->dateTime}}"
                                       min="2018-06-07T00:00" max="2018-06-14T00:00"
                                       class="form-control" disabled>
                            </div>
                            <div class="form-group">
                                <label for="amount"><?php echo __('main.amount'); ?></label>
                                <input type="number" step="0.01" class="form-control" id="amount" name="amount" value="{{$order->amount}}">
                            </div>
                            <div class="form-group">
                                <label for="amountVTA"><?php echo __('main.amountVTA'); ?></label>
                                <input type="number" step="0.01" class="form-control" id="amountVTA" name="amountVTA" value="{{$order->amountVTA}}">
                            </div>
                        </div>
                        <!-- /.card-body -->
                        <div class="card-footer">
                            <input type="submit" class="btn btn-primary float-right">
                        </div>
                    </div>
                </form>
            </div>

        </div>
    </div>
@stop

resources/views/order/index.blade.php
@extends('adminlte::page')

@section('title', 'AliSales')
@section('content_header')
    <h1 class="m-0 text-dark"><?php echo __('main.orders'); ?></h1>
@stop

@section('content')

    <table id="example" class="table table-bordered table-striped datatable dataTable no-footer" style="width:100%">
        <thead>
        <tr>
            <th><?php echo __('main.customer'); ?></th>
            <th><?php echo __('main.dateTime'); ?></th>
            <th><?php echo __('main.amount'); ?></th>
            <th><?php echo __('main.amountVTA'); ?></th>
            <th></th>
        </tr>
        </thead>
        <tbody>

        <!-- limité à 30 afin que la page ne charge pas tous les éléments -->
        @foreach ($orders as $order)
            <x-order.tr :order=$order> </x-order.tr>
        @endforeach

        </tbody>
        <tfoot>
        <tr>
            <th><?php echo __('main.customer'); ?></th>
            <th><?php echo __('main.dateTime'); ?></th>
            <th><?php echo __('main.amount'); ?></th>
            <th><?php echo __('main.amountVTA'); ?></th>
            <th></th>
        </tr>
        </tfoot>
    </table>
@stop
@section('js')
    <script>
        $(document).ready(function () {
            $('#example').DataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/French.json"
                }
            });
        });
    </script>
@stop

resources/views/order/show.blade.php
@extends('adminlte::page')

@section('title', 'AliSales')
@section('content_header')
    <h1 class="m-0 text-dark"><?php echo __('main.orders'); ?></h1>
@stop

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card card-primary card-outline">
                    <div class="card-body box-profile">
                        <h3 class="profile-username text-center">{{$order->dateTime}}</h3>

                        <ul class="list-group list-group-unbordered mb-3">
                            <li class="list-group-item">
                                <b><?php echo __('main.amount'); ?></b> <span class="float-right">{{$order->amount}}</span>
                            </li>
                            <li class="list-group-item">
                                <b><?php echo __('main.amountVTA'); ?></b> <span class="float-right">{{$order->amountVTA}}</span>
                            </li>
                            <li class="list-group-item">
                                <b><?php echo __('main.customer'); ?></b> <span class="float-right">{{$order->customer->name}}</span>
                            </li>
                        </ul>

                        <a href="{{route('order.edit', ['order'=>$order])}}" class="btn btn-primary btn-block"><b><?php echo __('main.modify'); ?></b></a>
                    </div>
                    <!-- /.card-body -->
                </div>
            </div>
        </div>
    </div>
@stop